ngx-rocket/generator-ngx-rocket

generators/app/templates/docs/coding-guides/__ionic.ionic.md
Following the remarks from [this thread](https://forum.ionicframework.com/t/a-complete-ionic-starter-based-on-angular-cli-check-it-out/100842/13), here is a quick update of the Ionic doc concerning the CLI limitations.
Suggestions welcome.
=> More precision on limitations

generators/app/templates/docs/coding-guides/angular.md
Slight update with a few more words and a new section about performance.
=> Updated Angular intro

generators/app/templates/_package.json
=> Update Angular Material to 5.0.0-rc0

generators/app/index.js, generators/app/options.json, generators/app/templates/_karma.conf.js, generators/app/templates/_package.json
Work in progress
TODO
- update generator doc with options flags
=> Added option flag to allow using existing Chrome install

.circleci/config.yml
Add a minimalist circleci config to disable circleci build error on each branch. Temporay fix to wait proper implementation of #162
=> Add minimalist circleci config

generators/app/index.js
TypeError: Cannot set property 'ui' of undefined
=> * [bug] the raw ui option can not work

generators/app/templates/src/app/core/http/api-prefix.interceptor.spec.ts, generators/app/templates/src/app/core/http/api-prefix.interceptor.ts
=> Avoid interception of full-path specified urls

generators/app/templates/docs/coding-guides/angular.md
The FAQ section is essentially just a link for now, but do not hesitate to make it grow with some of the recurrent questions that arises in issues 😄
=> Updated angular guide with a FAQ section and added NGXS references

README.md, cli/index.js, generators/addon/index.js, generators/addon/prompts.js, generators/app/index.js, generators/app/options.js, generators/app/prompts.js, package-lock.json, package.json
=> Migrated generator code base to xo + prettier and async/await

generators/app/templates/src/app/__material.material.module.ts
=> Add missing Material modules

generators/app/templates/_package.json
wrong `translations:extract` --sort parameter
=> wrong `translations:extract` --sort parameter

generators/app/templates/_package.json
update ng-bootstrap version to 4.x.x for angular 7.x.x
=> update ng-bootstrap version to 4.x.x

README.md, generators/app/index.js, generators/app/prompts.js, generators/app/templates/_README.md, generators/app/templates/_package.json, generators/app/templates/src/app/core/http/http-cache.service.ts, generators/app/templates/src/app/core/i18n.service.ts, scripts/tests/app/web/bootstrap.json, scripts/tests/app/web/raw.json
Also remove default Lodash inclusion in favor of Vanilla JS, and move
it to an option.
=> Add optional utility libraries choice (#381)

generators/app/templates/proxy.conf.js
This PR should replace #417 since we have no feedback from the original submitter.
=> Updated link to Angular docs for more relevance

generators/app/templates/_package.json
Version upgraded because I received a security warning from Github.
=> Update lodash dependency to 4.7.11

generators/app/templates/_package.json
=> Roll back core-js version

README.md, cli/index.js, generators/app/index.js, generators/app/options.js
- Add support to ngx CLI for `--skip-welcome` and `--addons` options
- Add `--skip-quickstart` generator option to disable quick start message
=> Add options for dropshipping generator

generators/app/templates/src/app/_app.component.ts
I'm not positive this is needed and haven't measured an actual problem, but better safe than sorry and I think it's more expressive of intent to use switchMap anyway.
=> fix: avoid potential never-ending subscriptions for page titles

generators/app/templates/src/_index.html
Fix for #305 inspired by https://github.com/strvcom/strv-react-scripts/commit/d766b0e13f6447ed3bfaf8e1d68739372a66965b and others.
=> Fix favicons being loaded on every route change

generators/app/index.js
This pull request is related to #494 - it fixes the problems discussed
=> Fixed insight issue causing ngx CLI crash

generators/app/index.js
Note that it might seems cryptic as it cannot be used as-is, but it's preparatory work for something nice coming :wink:
=> Autofix add-ons names from package ref

generators/app/templates/src/translations/__es-ES._es-ES.json, generators/app/templates/src/translations/__it-IT._it-IT.json
Added template json for Italian and Spanish
=> feat: add spanish and italian languages

generators/app/templates/docs/coding-guides/__ionic.ionic.md, generators/app/templates/docs/coding-guides/e2e-tests.md
Sorry, I missed a couple of spaces in my previous pull request.
=> chore: remove redundant spaces in docs

generators/app/templates/src/app/i18n/__ionic.language-selector.component.html, generators/app/templates/src/app/settings/__ionic-tabs._settings.component.html
https://github.com/ionic-team/ionicons/blob/master/CHANGELOG.md
=> fix: update ionic icon names

generators/app/templates/_package.json
Update all packages to match latest Angular 10.1.*
=> feat: update app dependencies

README.md, package.json
oops! was forgotten in last update
=> docs: update angular version

generators/app/templates/src/translations/__pt-BR._pt-BR.json
Added template json for Brazilian Portuguese (pt-BR)
=> feat: add brazilian portuguese language

generators/app/templates/_package.json
=> fix: rename env script to fix execution in some environments (closes #575)
